version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: edgeiq
    ports: ["5432:5432"]
    volumes: [ "pgdata:/var/lib/postgresql/data" ]

  backend:
    build: ../backend
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/edgeiq
    ports: ["8000:8000"]
    depends_on: [postgres]

  frontend:
    build: ../frontend
    ports: ["5173:80"]
    depends_on: [backend]

volumes:
  pgdata:
