[tool.black]
line-length = 100
target-version = ["py311"]
exclude = '''
/(
  \.git
 | \.venv
 | build
 | dist
)/
'''

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E203"]
