FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PYTHONPATH=/app
ENV PYTHONPATH=/app
COPY requirements.txt .
RUN pip install -U pip && pip install -r requirements.txt && pip install alembic
COPY app ./app
COPY alembic.ini .
COPY alembic ./alembic
CMD ["alembic","upgrade","head"]
